"""Workflow registry for version management.

Auto-generated by Operandai CLI — do not edit manually.
"""
# Updated: 2026-09-10T17:54:28.922171Z

from typing import Any

from .c_gpflip1.workflow import GateProbeFlip_gpflip1Workflow as _c_gpflip1


WORKFLOW_REGISTRY: dict[str, type[Any]] = {
    "gpflip1": _c_gpflip1,
}
