"""Workflow registry for version management.

Auto-generated by Operandai CLI — do not edit manually.
"""
# Updated: 2026-09-10T17:40:22.287343Z

from typing import Any

from .c_gpnotrea.workflow import GateProbeNotReady_gpnotreaWorkflow as _c_gpnotrea


WORKFLOW_REGISTRY: dict[str, type[Any]] = {
    "gpnotready1": _c_gpnotrea,
}
