"""Workflow registry for version management.

Auto-generated by Operandai CLI — do not edit manually.
"""
# Updated: 2026-09-10T16:54:28.787777Z

from typing import Any

from .c_gateprob.workflow import GateProbe_gateprobWorkflow as _c_gateprob


WORKFLOW_REGISTRY: dict[str, type[Any]] = {
    "gateprobe1": _c_gateprob,
}
