"""Workflow registry for version management.

Auto-generated by Operandai CLI — do not edit manually.
"""
# Updated: 2026-09-10T17:40:23.680686Z

from typing import Any

from .c_gpreadon.workflow import GateProbeReadOnly_gpreadonWorkflow as _c_gpreadon


WORKFLOW_REGISTRY: dict[str, type[Any]] = {
    "gpreadonly1": _c_gpreadon,
}
