# @scaffold:constants constants.py
# @scaffold:process_id gate-probe-flip
# @scaffold:process_name "Gate Probe Flip"
# @scaffold:file_hash sha256:51a83b7b341995d6bc11da9bf1fcff7209c49699af62b5ea9530563db2acbc97
#
# PURPOSE: Central constants for the Gate Probe Flip process.
# This file is FULLY MANAGED by the scaffold generator and will be
# regenerated on sync. Do not add custom code here.
#
# CONVENTION: This file lives inside the version folder (c_<id>/) and
# is owned by that version. Files inside the same version folder import
# from it via absolute path:
#   from processes.fixture_tenant.gate_probe_flip.c_gpflip1.constants import STEP_X
#
# Each version owns its own copy so changes to a newer version cannot
# remove symbols that older versions depend on.
#
# CONTENTS:
# - TASK_QUEUE: Temporal task queue name for this process
# - Step constants: Lineage IDs for all process steps
# - Decision constants: Lineage IDs for all decision points
# - Outcome constants: Possible outcomes for each decision
# - Signal constants: Temporal signal names for human steps
# - Artifact constants: Lineage IDs for all artifacts
"""
Constants for the Gate Probe Flip process.

Lineage IDs are defined in the process export JSON and must match exactly
for proper event correlation and process tracking.

This file is automatically generated by the Operandai CLI.
Do not edit manually - changes will be overwritten on sync.
"""

# Task queue for this process
TASK_QUEUE = "gate-probe-flip"

# =============================================================================
# Step lineage IDs
# =============================================================================
# Resolve Read Workspace (SYSTEM)
# Session worktree for petclinic at main
# Entry point: Yes
STEP_RESOLVE_READ_WORKSPACE = "step-resolve"
# Create Feature Branch (SYSTEM)
# Feature branch gate-probe/<probe id>
STEP_CREATE_FEATURE_BRANCH = "step-branch"
# Gate Probe Code (AI)
# One mutating agent step so the readiness gate runs
# Exit point: Yes
STEP_GATE_PROBE_CODE = "step-code"

# =============================================================================
# Decision lineage IDs
# =============================================================================
# No decisions defined in this process

# =============================================================================
# Decision outcomes
# =============================================================================
# No outcomes (no decisions in this process)

# =============================================================================
# Signal names for Temporal workflow (HUMAN steps)
# =============================================================================
# No human steps in this process

# =============================================================================
# Artifact lineage IDs
# =============================================================================
# Resolve Read Workspace - Repository Key (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_REPOSITORY_KEY = "art-resolve-repo-key"
# Resolve Read Workspace - Base Branch Override (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_BASE_BRANCH_OVERRIDE = "art-resolve-branch-base"
# Resolve Read Workspace - Working Directory (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_WORKING_DIRECTORY = "art-resolve-wd"
# Resolve Read Workspace - Repository Key (out) (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_REPOSITORY_KEY_OUT = "art-resolve-repo-key-out"
# Resolve Read Workspace - Base Branch (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_BASE_BRANCH = "art-resolve-base-branch"
# Resolve Read Workspace - Base SHA (SIMPLE)
ARTIFACT_RESOLVE_READ_WORKSPACE_BASE_SHA = "art-resolve-base-sha"
# Create Feature Branch - Context Label (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_CONTEXT_LABEL = "art-branch-label"
# Create Feature Branch - Context ID (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_CONTEXT_ID = "art-branch-ctx-id"
# Create Feature Branch - Allow Branch Reuse (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_ALLOW_BRANCH_REUSE = "art-branch-allow-reuse"
# Create Feature Branch - Working Directory (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_WORKING_DIRECTORY = "art-branch-wd"
# Create Feature Branch - Branch Name (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_BRANCH_NAME = "art-branch-name"
# Create Feature Branch - Repository Key (SIMPLE)
ARTIFACT_CREATE_FEATURE_BRANCH_REPOSITORY_KEY = "art-branch-repo-key"
# Gate Probe Code - Task (SIMPLE)
ARTIFACT_GATE_PROBE_CODE_TASK = "art-code-task"
# Gate Probe Code - Success (SIMPLE)
ARTIFACT_GATE_PROBE_CODE_SUCCESS = "art-code-success"
# Gate Probe Code - Output (SIMPLE)
ARTIFACT_GATE_PROBE_CODE_OUTPUT = "art-code-output"
# Gate Probe Code - Commit SHA (SIMPLE)
ARTIFACT_GATE_PROBE_CODE_COMMIT_SHA = "art-code-commit"
# Gate Probe Code - Is Stuck (SIMPLE)
ARTIFACT_GATE_PROBE_CODE_IS_STUCK = "art-code-is-stuck"
